export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'dashboard',
    path: '/dashboard',
    title: '仪表盘',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'dir',
    componentPath: null,
    id: 1,
    pid: null,
  },
  {
    name: 'workbench',
    path: '/dashboard/workbench',
    title: '工作台',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    pinTab: true,
    menuType: 'page',
    componentPath: '/dashboard/workbench/index.vue',
    id: 2,
    pid: 1,
  },
  {
    name: 'monitor',
    path: '/dashboard/monitor',
    title: '监控页',
    requiresAuth: true,
    icon: 'icon-park-outline:anchor',
    menuType: 'page',
    componentPath: '/dashboard/monitor/index.vue',
    id: 3,
    pid: 1,
  },
  // 添加设备管理相关路由
  {
    name: 'device',
    path: '/device',
    title: '设备管理',
    requiresAuth: true,
    icon: 'icon-park-outline:cpu',
    menuType: 'dir',
    componentPath: null,
    id: 460,
    pid: null,
  },
  {
    name: 'deviceList',
    path: '/device/list',
    title: '设备列表',
    requiresAuth: true,
    icon: 'icon-park-outline:all-application',
    menuType: 'page',
    componentPath: '/device/list/index.vue',
    id: 461,
    pid: 460,
  },
  {
    name: 'deviceType',
    path: '/device/type',
    title: '设备类型',
    requiresAuth: true,
    icon: 'icon-park-outline:category-management',
    menuType: 'page',
    componentPath: '/device/type/index.vue',
    id: 462,
    pid: 460,
  },
  {
    name: 'deviceLog',
    path: '/device/log',
    title: '设备日志',
    requiresAuth: true,
    icon: 'icon-park-outline:file-history',
    menuType: 'page',
    componentPath: '/device/log/index.vue',
    id: 463,
    pid: 460,
  },
  {
    name: 'collector',
    path: '/device/collector',
    title: '采集器管理',
    requiresAuth: true,
    icon: 'icon-park-outline:data-server',
    menuType: 'page',
    componentPath: '/device/collector/index.vue',
    id: 464,
    pid: 460,
  },
  {
    name: 'collectTask',
    path: '/device/task',
    title: '采集任务',
    requiresAuth: true,
    icon: 'icon-park-outline:schedule',
    menuType: 'page',
    componentPath: '/device/task/index.vue',
    id: 465,
    pid: 460,
  },
]
