---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 周东明.
--- DateTime: 2024/12/3 13:37
---
package.path = "./plugin/2022F857-33/?.lua;"

require "utils"
require "json"
-------公共函数
-- 校验和
function checkSum(buffer, startIndex, endIndex)
    local sum = 0

    for i = startIndex, endIndex do
        sum = sum + buffer[i]
    end

    return sum % 256
end

-- 地址转换 2 ~ 9 字节
function convertAddress(requestADU, sAddr)
    local addr = string.format("%014d", tonumber(sAddr))
    requestADU[3] = tonumber(string.sub(addr, 13, 14), 16)
    requestADU[4] = tonumber(string.sub(addr, 11, 12), 16)
    requestADU[5] = tonumber(string.sub(addr, 9, 10), 16)
    requestADU[6] = tonumber(string.sub(addr, 7, 8), 16)
    requestADU[7] = tonumber(string.sub(addr, 5, 6), 16)
    requestADU[8] = tonumber(string.sub(addr, 3, 4), 16)
    requestADU[9] = tonumber(string.sub(addr, 1, 2), 16)
end

-- GenerateCommand
function GenerateCommand(sAddr,cmd)
    --                               |<---------------地址--------------->|    ctrl  dataLen                       checkSum
    --                   1     2     3     4     5     6     7     8     9     10    11    12    13    14    15    16
    local requestADU = { 0x68, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x03, 0x90, 0x1F, 0x00, 0x3D, 0x16 }
    --                  [68 10 12 00 00 00 00 00 00 01 03 1F 90 00 3D 16]
    -- 地址转换 3 ~ 9 字节
    convertAddress(requestADU, sAddr)
    -- cmd 11 ~ 14 字节
    requestADU[12] = cmd[1]
    requestADU[13] = cmd[2]
    -- 校验和
    requestADU[15] = checkSum(requestADU, 1, 14)
    -- 在requestADU前面插入 3个 0xFE
    for i = 1, 3 do
        table.insert(requestADU, 1, 0xFE)
    end
    return requestADU
end

function WriteCommand(sAddr, cmd)
    --                               |<---------------地址--------------->|    ctrl  dataLen                       checkSum
    --                   1     2     3     4     5     6     7     8     9     10    11    12    13    14    15    16    17
    local requestADU = { 0x68, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2A, 0x04, 0xA0, 0X17, 0x00, 0x99, 0x3D, 0x16 }
    --                  [ 68 10 01 26 02 16 20 00 00 2A 04 17 A0 00 55 11 16 ]
    -- 地址转换 2 ~ 8 字节
    convertAddress(requestADU, sAddr)
    -- cmd 12 ~ 15 字节
    requestADU[12] = cmd[1]
    requestADU[13] = cmd[2]
    requestADU[14] = cmd[3]
    requestADU[15] = cmd[4]
    -- 校验和
    requestADU[16] = checkSum(requestADU, 1, 17)
     -- 在requestADU前面插入 3个 0xFE
     for i = 1, 3 do
        table.insert(requestADU, 1, 0xFE)
    end
    return requestADU
end

-- 关阀
function GenerateCloseValve(sAddr)
    local cmd = { 0xA0, 0x17, 0x00, 0x99 }
    return WriteCommand(sAddr, cmd)
end

-- 开阀
function GenerateOpenValve(sAddr)
    local cmd = { 0xA0, 0x17, 0x00, 0x55}
    return WriteCommand(sAddr, cmd)
end
-- go 程序接收到表具数据，放到rxBuf中，从而供AnalysisRx解析
rxBuf = {}
function AnalysisRx(sAddr, rxBufCnt)
    -- 最短指令12个字节
    -- 68 10 04 00 05 24 00 00 00 81 16 90 1F 00 00 05 00 00 2C 00 05 00 00 2C 00 00 00 00 00 00 00 00 FF 4C 16
    if (rxBufCnt < 16) then
        rxBuf = {}
        -- Status = "1" 错误
        print("error:rxBufCnt < 12")
        return { Status = "1", Variable = {} }
    end
     -- 查找起始符0x68
     local startIndex = 1
     while rxBuf[startIndex] ~= 0x68 do
         startIndex = startIndex + 1
         if startIndex > #rxBuf then
             error("0x68起始符未找到")
             return
         end
     end
     -- 移除0xFE唤醒符
     while startIndex > 1 and rxBuf[startIndex - 1] == 0xFE do
         table.remove(rxBuf, startIndex - 1)
         startIndex = startIndex - 1
     end

    local endFlag
    local endIndex = 0
    local csFlag
    for i = 1, #rxBuf do
        if (rxBuf[i] == 0x16) then
            print("i:".. i, string.format("%X", rxBuf[i-1]), string.format("%X", rxBuf[i]))
            local cs = checkSum(rxBuf, 1, i - 2)
            if (cs == rxBuf[i-1]) then
                endFlag = rxBuf[i]
                csFlag = rxBuf[i-1]
                endIndex = i
                break
            end
        end
    end
    -- 地址 3~9字节
    local mAddr = string.format("%02X%02X%02X%02X%02X%02X%02X",
                    rxBuf[9], rxBuf[8], rxBuf[7], rxBuf[6], rxBuf[5], rxBuf[4], rxBuf[3])
    local addr = string.format("%014d", tonumber(sAddr))
    if (mAddr ~= addr) then
        rxBuf = {}
        print("error:mAddr ~= sAddr")
        return { Status = "1", Variable = {} }
    end
    -- 命令 12~13字节

    local cmd = string.format("%02X%02X", rxBuf[12], rxBuf[13])
    dataIndex = 15
    data = {}
    -- 90 1F
    if cmd == "901F" or cmd == "1F90" then
        -- 直到找到结束标志2C
        while (rxBuf[dataIndex] ~= 0x2C) do
            data[#data+1] = rxBuf[dataIndex]
            dataIndex = dataIndex + 1
        end
        local n = ""
        for i = #data, 1, -1 do
            n = n.. string.format("%02X", data[i])
        end
        dev_flow = tonumber(n, 10)
        print("dev_flow:".. dev_flow, dev_flow/100.0)
        rxBuf = {}
        return { Status = "0", Variable = {
            utils.AppendVariable(0, "dev_flow", "总流量", "double", dev_flow,
                    string.format("%.2f", dev_flow / 100.0))
        }
        }
    -- A0 17
    elseif cmd == "A017" or cmd == "17A0" then
        local status = string.format("%02X%02X", rxBuf[dataIndex],rxBuf[dataIndex+1])
        if status == "02FF" then
            -- close
            return { Status = "0", Variable = {
                utils.AppendVariable(0, "dev_status", "阀门状态", "string", status,
                        "0")
            }
            }
        elseif status == "00FF" then
            -- open
            return { Status = "0", Variable = {
                utils.AppendVariable(0, "dev_status", "阀门状态", "string", status,
                        "1")
            }
            }
        end
    end
    rxBuf = {}
    return { Status = "1", Variable = {} }
end

function GenerateGetFlow(sAddr, continued)
    local requestADU = GenerateCommand(sAddr,{0x90,0x1F})
    return { Status = continued, Variable = requestADU }
end


function GenerateGetRealVariables(sAddr, step)
    print("2019F302-33 ver 1.0", sAddr, step)
    if (step == 0)
    then
        return GenerateGetFlow(sAddr, "0")
    end
end

function DeviceCustomCmd(sAddr, cmdName, cmdParam, step)
    local params = json.jsondecode(cmdParam)
    if (cmdName == "dev_flow") then
        return GenerateGetFlow(sAddr)
    elseif (cmdName == "OpenValve") then
        return GenerateOpenValve(sAddr)
    elseif (cmdName == "CloseValve") then
        return GenerateCloseValve(sAddr)
    end
    return { Status = "0", Variable = {} }
end