---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/6 09:07
---
package.path = "./plugin/DDSU5886/?.lua;"

require "utils"
require "json"
require "crc"

-- subArray
function subArray(arr, start, count)
    local result = {}
    for i = start, start + count - 1 do
        table.insert(result, arr[i])
    end
    return result
end
-- GenerateCommand
function GenerateCommand(sAddr,cmd)
    --                   地址  功能码  |<数据内容>|             |<-CRC16->|
    local requestADU = { 0x00, 0x04, 0x00, 0x1D, 0x00, 0x02, 0xE0, 0x1C}
    requestADU[1] = tonumber(sAddr)
    -- 数据内容
    requestADU[3] = cmd[1]
    requestADU[4] = cmd[2]
    -- CRC16
    local arr = subArray(requestADU, 1, 6)
    local crc1, crc2 = CRC16(arr)
    print("CRC16", crc1, crc2)
    requestADU[7] = crc1
    requestADU[8] = crc2
    -- 输出每个字节
    for i = 1, #requestADU do
        print(string.format("%02X", requestADU[i]))
    end
    return requestADU
end

function GenerateGetConsumption(sAddr, step)
    local requestADU = GenerateCommand(sAddr, { 0x00, 0x1D })
    return { Status = 0, Variable = requestADU }
end

rxBuf = {}

-- AnalysisRx 解析接收到的数据
function AnalysisRx(sAddr, rxBufCnt)
    -- 1. 数据解析
    if tonumber(rxBuf[1],16) ~= tonumber(sAddr,10) and
    tonumber(rxBuf[1],16) ~= tonumber(sAddr,16) then
        print("地址错误")
        rxBuf = {}
    return { Status = "1", Variable = {} }
    end
    local fun = rxBuf[2]
    local len = rxBuf[3]
    local data = subArray(rxBuf, 4, len)
    local crc = subArray(rxBuf, len + 4, 2)
    local crc161,crc162 = CRC16(subArray(rxBuf, 1, len + 3))

    if crc161 ~= crc[1] or crc162 ~= crc[2] then
        print("crc校验错误")
        rxBuf = {}
        return
    end
    -- 2. 数据处理
    if fun == 0x04 or fun == 0x03 then
        -- 读取数据
        local n = ""
        for i = 1, #data do
            n = n.. string.format("%02X", data[i])
        end
        val = tonumber(n, 16)
        return { Status = "0", Variable = {
            utils.AppendVariable(0, "dev_consumption", "总电能", "double", val,
                    string.format("%.2f", val / 100.0))
        }
        }
    elseif fun == 0x10 then
        return { Status = "0", Variable = {} }
    end
end

function GenerateGetRealVariables(sAddr, step)
    print("DDSY1829", sAddr, step)
    if (step == 0) then
        return GenerateGetConsumption(sAddr, "1")
    end
end

-- 自定义命令处理
function DeviceCustomCmd(sAddr, cmdName, cmdParam, step)
    local params = json.jsondecode(cmdParam)
    if (cmdName == "dev_consumption") then
        return GenerateGetConsumption(sAddr)
    end
    return { Status = "0", Variable = {} }
end
